global.fullRemovals.push(
    /biomesoplenty:.*willow*./,
    /compatoplenty:.*willow*./,
    /decorative_compat:.*willow*./,
    'biomesoplenty:spanish_moss',
    /biomesoplenty:.*magic*./,
    /compatoplenty:.*magic*./,
    /decorative_compat:.*magic*./,
    /biomesoplenty:.*umbran*./,
    /compatoplenty:.*umbran*./,
    /decorative_compat:.*umbran*./,
)