
#Graphics settings
[graphics]
	#Enable better particle/effect layering. Fixes particles and effects rendering behind clouds and weather. NOTE: Does NOT work with fabulous graphics mode.
	betterLayering = true

