
#Vanilla gameplay tweaks
[tweaks]
	#Nerfs Boats ability to go extremely fast when on ice and other splippery blocks (off by default).
	"Ice Boat Nerf" = false
	#Stops Flower Pots being able to be placed in the air.
	"Floating Flower Pots Fix" = true
	#Tall Birch Trees will generate branches growing out the side of the tree.
	"Birch Branches" = true

